---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	preprocess(preprocess)
	incomplete_handler(incomplete_handler)
	topic_specialist(topic_specialist)
	urgency_specialist(urgency_specialist)
	missing_info_specialist(missing_info_specialist)
	validation_gate(validation_gate)
	semantic_reviewer(semantic_reviewer)
	risk_guardrail(risk_guardrail)
	deterministic_router(deterministic_router)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> preprocess;
	deterministic_router --> finalize;
	incomplete_handler --> finalize;
	missing_info_specialist --> validation_gate;
	preprocess -. &nbsp;incomplete&nbsp; .-> incomplete_handler;
	preprocess -. &nbsp;classify&nbsp; .-> topic_specialist;
	risk_guardrail --> deterministic_router;
	semantic_reviewer --> risk_guardrail;
	topic_specialist --> urgency_specialist;
	urgency_specialist --> missing_info_specialist;
	validation_gate -. &nbsp;guardrail&nbsp; .-> risk_guardrail;
	validation_gate -. &nbsp;review&nbsp; .-> semantic_reviewer;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
